### ISSUE TITLE
Code Style & Quality Assurance

### ISSUE THREAD

**Issue by DeC0rtez** [DeC0rtez/SC_ChatBot#11]
As per the assignment brief: 

The code should be well written following the [style practices for writing Clojure code](https://guide.clojure.style/). It should be clearly and reasonably commented with docstrings and regular comments where necessary. The code uses the properties of Clojure and the available computational resources efficiently (e.g., no unnecessary code blocks or repetitions).

Maximum points: **20%**

This is a crucial part of our assignment and grants us seemingly free points we really don'tt want to miss out on. While we should ideally follow these conventions while writing code, we are newbies at this and clojure is a beast of its own category. It would be ideal to have someone study up on the clojure coding style. This person would then review code structure (not functionality/ bugfixing) and make it comply by the guidelines before commiting to the master branch.

**HIGH PRIORITY**

**Comment by DeC0rtez** [comment]
@Vladyslav48 @ndr-power One of you guys should take this. Reach out when you do and feel free to unassign the others from the issue.

**Comment by DeC0rtez** [comment]
[park-info.clj](https://github.com/DeC0rtez/SC_ChatBot/blob/develop/park_info.clj) on the [develop](https://github.com/DeC0rtez/SC_ChatBot/tree/develop) branch is ready for a coding style check.

**Comment by ndr-power** [comment]
Already done some code style checks on proto, fixed some common issues.

**Comment by DeC0rtez** [comment]
Done by Nikita. Issue closed.
