### ISSUE TITLE
ICA2: small QoL fixes

### ISSUE THREAD

**Issue by DeC0rtez** [DeC0rtez/SC_ChatBot#22]
We need to make fixes to our ICA1 chatbot based on provided feedback. Namely:
- **Error handling**: fix issues where bot behaves unecpectedly in cases of unrecognized words, spelling errors, etc.
- **Park names**: the bot currently uses park names as they are stored in the data, e.g. obora_hvezda. This should be sanitized to be more user friendly and should appear as: Obora Hvezda.
- **Enhanced park name recognition**: the bot should be able to associate park names with the numbers they are listed under before the dialogue loop, and should also be able to interpret czech spelling letters such as ě, í, ý, etc.
- **Add unix dialogue ending keywords**: add "exit" & "quit" to set of dialogue ending words
- more TBA

**Comment by DeC0rtez** [comment]
- Fixed multiple issues where bot acts strangely when a keyword is not detected.
- Added unix dialogue ending keywords
- Added more keywords for better comprehension of user inputs

**Comment by ndr-power** [comment]
Added support of Czech letters to park identifier

**Comment by ndr-power** [comment]
Added park recognition loop, so it doesn't fail when a string doesn't have a park name in it.

**Comment by Vladyslav48** [comment]
Added park name capitalization and pretty-print without underscores.

**Comment by DeC0rtez** [comment]
QoL fixes completed and implemented.
