### ISSUE TITLE
Text/ keyword detection

### ISSUE THREAD

**Issue by DeC0rtez** [DeC0rtez/SC_ChatBot#8]
We need a function that will scan a string, detect keywords, match them against our data and return information based on them. 

**Example:**

user> Can I bring my dog to the park?
**Response if :dogs false**
bot> Unfortunately, this park does not allow dogs.
**Response if :dogs true**
bot> Yes, you may bring your 4 legged companion to this park!

note: the bot should be able to detect and take into account common alternative words. For example: dog, doggy, doggo, etc.

**Comment by DeC0rtez** [comment]
@ndr-power @Vladyslav48 One of you guys could take this.

**Comment by DeC0rtez** [comment]
Simple & useful:
https://www.programming-idioms.org/idiom/39/check-if-string-contains-a-word/2621/clojure

**Comment by DeC0rtez** [comment]
Stuff you can use for a simple detection function. Checks if word is in a set, prints output based on that condition. Use of set data structure is recommended.

(def test_set #{"car", "vehicle", "automobile", "ride"})
(println "input word:")
(def x (read-line))
(cond
->(contains? test_set x) (println "Is in set")
->(not (contains? test_set x)) (println "Is not in set")
->:else "zero")

**Comment by ndr-power** [comment]
Done the task with @Vladyslav48, I opened a pull request

**Comment by DeC0rtez** [comment]
Applied and integrated in prototype.clj. Closing issue.
